from flask import Flask,request,jsonify

import spacy
from spacy.lang.en.stop_words import STOP_WORDS
from string import punctuation
from heapq import nlargest


app = Flask(__name__)

@app.route('/')
def home():
    return "hello world"

@app.route('/analyze',methods=['GET'])
def analyze():

    # # rawtext = request.form.get('text')
    # rawtext="""Jaipur: Rajasthan Chief Minister Ashok Gehlot is all set for a big-ticket budget ahead of the state elections due later this year. The state budget -- due to be presented in the state assembly today -- is being promoted with a catchy tag line "Bachat, Rahat, Badhat" meaning "Savings, Relief, Prosperity.
    # Hoardings, featuring the smiling face of the Chief Minister, dot the state. Advertisements are regularly appearing in newspapers. Mr Gehlot, who also holds the finance portfolio, will present the budget at 11 am.
    # "Rajasthan's budget will bring savings, relief and progress. Finalised the budget 2023 with the resolution of ensuring #Bachat_Rahat_Badhat of every person of the state," he tweeted on Thursday.
    # Ahead of the budget, Chief whip Mahesh Joshi had said, "It is the first time a Chief Minister is presenting a budget with so much enthusiasm and energy. The focus of this budget is savings, relief and increase in incomes. The entire concept of the budget is before the people, who are hoping that he will fulfil expectations".
    # That Ashok Gehlot is going all out to woo the electorate was clear from his announcement in Alwar during the Bharat Jodo Yatra in December last year. He had announced a huge subsidy in cooking gas -- upto ₹ 400 -- to 1 crore needy people of the state.
    # The government is hoping to cash in on the goodwill generated by social security schemes. There is expectation that the Health insurance cover under the Chiranjeevi Beema Yojana could be upped and the old pension scheme be brought back.
    # There is also a possibility that the urban employment scheme on the lines of MNREGA being provided in the cities could see more allocations.
    # With an eye on the vote of the state's young people -- around 4 per cent of the state's population -- the government has issued a circular to all colleges to make arrangements to see the budget live."""
    # stopwords=list(STOP_WORDS)   #stop words
    # #print(stopwords)
    # nlp = spacy.load('en_core_web_sm')      #small module of spacy
    # doc =nlp(rawtext)
    # # print(doc)
    # tokens = [token.text for token in doc]
    # # print(tokens)
    # word_freq={}
    # for word in doc:
    #     if word.text.lower() not in stopwords and word.text.lower() not in punctuation:
    #         if word.text not in word_freq.keys():
    #             word_freq[word.text]=1
    #         else:
    #             word_freq[word.text]+=1
        
    # # print(word_freq)

    # max_freq= max(word_freq.values())

    # for word in word_freq.keys():
    #     word_freq[word]=word_freq[word]/max_freq

    # # print(word_freq)

    # sen_tokens=[sent for sent in doc.sents]
    # # print(sen_tokens)
    # sent_scores={}
    # for sent in sen_tokens:
    #     for word in sent:
    #         if word.text in word_freq.keys():
    #             if sent not in sent_scores.keys():
    #                 sent_scores[sent]=word_freq[word.text]
    #             else:
    #                 sent_scores[sent]+=word_freq[word.text]

    # # print(sent_scores)
    # select_len =int(len(sen_tokens)*0.3)
    # summary = nlargest(select_len, sent_scores, key=sent_scores.get)
    # final_summary = [word.text for word in summary]
    # summary =' '.join(final_summary)
    result= {'text':'''Jaipur: Rajasthan Chief Minister Ashok Gehlot is all set for a big-ticket budget ahead of the state elections due later this year. The state budget -- due to be presented in the state assembly today -- is being promoted with a catchy tag line "Bachat, Rahat, Badhat" meaning "Savings, Relief, Prosperity.
    # Hoardings, featuring the smiling face of the Chief Minister, dot the state. Advertisements are regularly appearing in newspapers. Mr Gehlot, who also holds the finance portfolio, will present the budget at 11 am.
    # "Rajasthan's budget will bring savings, relief and progress. Finalised the budget 2023 with the resolution of ensuring #Bachat_Rahat_Badhat of every person of the state," he tweeted on Thursday.
    # Ahead of the budget, Chief whip Mahesh Joshi had said, "It is the first time a Chief Minister is presenting a budget with so much enthusiasm and energy. The focus of this budget is savings, relief and increase in incomes. The entire concept of the budget is before the people, who are hoping that he will fulfil expectations".
    # That Ashok Gehlot is going all out to woo the electorate was clear from his announcement in Alwar during the Bharat Jodo Yatra in December last year. He had announced a huge subsidy in cooking gas -- upto ₹ 400 -- to 1 crore needy people of the state.
    # The government is hoping to cash in on the goodwill generated by social security schemes. There is expectation that the Health insurance cover under the Chiranjeevi Beema Yojana could be upped and the old pension scheme be brought back.
    # There is also a possibility that the urban employment scheme on the li'''}

    return jsonify({'Summary':result})

    
if __name__ == '__main__':
    app.run(debug=True)
    